- name: Setup Common Configuration
  hosts: hadoop
  become: yes
  roles:
    - common

- name: Setup Ambari Server
  hosts: ambari-servers
  become: yes
  roles:
    - ambari-server
  
  vars:
    db_hostname: "<HOSTNAME>"
    db_port: "5432"
    db_name: "ambari"
    db_user: "ambari"
    db_password: "ambari"
    java_home: "/usr/lib/jvm/java-8-openjdk-amd64"

- name: Setup Ambari Agent
  hosts: ambari-agents
  become: yes
  roles:
    - ambari-agent
